# minikube.yml
---
- name: Install Minikube package directly
  yum:
    name: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    state: present
    disable_gpg_check: yes

- name: Start Minikube as the specified user
  command: su - "{{ user.stdout }}" -c "minikube start"

