# minikube.yml
---
- name: Install minikube package
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    state: present

- name: Start Minikube as the specified user
  command: su - "{{ user.stdout }}" -c "minikube start"

