# kubectl.yml
---
- name: Fetch latest stable version of kubectl
  uri:
    url: "https://dl.k8s.io/release/stable.txt"
    return_content: yes
  register: kubectl_version

- name: Download kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

